title: Tomek
description: Moja strona
baseurl: "" # bez "/" je≈õli strona jest na root repo
url: "https://janzbedny.github.io"
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
